#Routes http://localhost:8090 to http://localhost:8080/SampleMicroservice
server:
  port: 8080

zuul:
  routes:
    SampleMicroservice:
      url: http://localhost:8090

eureka:
  client:
    enabled: true
    registerwitheureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance